### ISSUE TITLE
Unauthenticated API

### ISSUE THREAD

**Issue by gshotwell** [canlii/API_documentation#1]
Good morning, I was wondering if there was any chance to create an unauthenticated API for some of Canlii's information? I'm working on an open source writing tool which automatically fills in citations for facta.

**Comment by alazear** [comment]
Good morning Gordon! Thank you for your question. While an unauthenticated API is not something we would typically provide, you are welcome to send a request to our tech team with more information about your project for consideration. Thank you! https://www.canlii.org/en/feedback/feedback.html
